 insert into category (id, created_date, active, category) values (1, now(), true, 'Beauty');
 insert into category (id, created_date, active, category) values (2, now(), true, 'Baby And Kids');
 insert into category (id, created_date, active, category) values (3, now(), true, 'Foot Wear');
 insert into category (id, created_date, active, category) values (4, now(), true, 'Clothing');
 insert into category (id, created_date, active, category) values (5, now(), true, 'Furniture');
 insert into category (id, created_date, active, category) values (6, now(), true, 'Jewellery');
 insert into category (id, created_date, active, category) values (7, now(), true, 'Electronics');
 insert into category (id, created_date, active, category) values (8, now(), true, 'Home Decor');
 insert into category (id, created_date, active, category) values (9, now(), true, 'Appliances');
 
 insert into product_details (category_id, name, description, mrp, actual_price, currency_code, image_url, available_stock, in_stock, active, created_date) values (1, 'LOreal Paris Infallible 24H Fresh Wear Foundation, 125 Natural Rose, 30 ml', 'Be unstoppable up to 24hr fresh wear foundation provides medium-to-full buildable coverage that lasts all day and allows the skin to breathe.', 1200, 899, 'INR', 'https://m.media-amazon.com/images/I/41o9Qe9KSEL._SL1001_.jpg', 200, true, true, now());
 insert into product_details (category_id, name, description, mrp, actual_price, currency_code, image_url, available_stock, in_stock, active, created_date) values (3, 'BATA Womens Lille Fashion Sandals', 'The product will be an excellent pick for you. It ensures an easy maintenance.', 1003, 776, 'INR', 'https://m.media-amazon.com/images/I/719GN+izopL._UL1500_.jpg', 2, true, true, now());
 insert into product_details (category_id, name, description, mrp, actual_price, currency_code, image_url, available_stock, in_stock, active, created_date) values (3, 'US Polo Association Mens Abor Sneakers', 'U.S. Polo Assn. is officially sanctioned by the United States Polo Association, the governing body for the sport of polo in the United States since 1890. U.S. Polo Assn. captures the authenticity of the sport while reflecting its rich history, and stays true to its roots in classic American style updated to complement today’s on-the-go lifestyle. The brand has a presence in over 135 countries, and offers clothing for men, women and children, as well as accessories, luggage, watches, shoes, home furnishings and more.',2999, 1641, 'INR', 'https://m.media-amazon.com/images/I/71TQIDUEKFS._UL1500_.jpg', 12, true, true, now());
 insert into product_details (category_id, name, description, mrp, actual_price, currency_code, image_url, available_stock, in_stock, active, created_date) values (5, 'Amazon Brand - Solimo Delphi 3 Seater Leatherette Fabric Recliner (Brown)', 'This high-quality recliner is made from strong and durable seams to ensure longevity. Its color does not fade with rubbing, so it looks new for a long time. With an attractive brown color, this comfortable recliner is an elegant addition to your home', 62000, 36899, 'INR', 'https://m.media-amazon.com/images/I/71QB8+U+hXL._SL1500_.jpg', 1, true, true, now());
 insert into product_details (category_id, name, description, mrp, actual_price, currency_code, image_url, available_stock, in_stock, active, created_date) values (2, 'Cutieco 250 ml Round Shape Baby Feeding Bottle, Multicolor - (Pack of 2)', 'Cutieco brings fine range of essential feeding bottles for your little one. Fedding bottles are a basic need for every parent to feed their babies and hence are most used. These are designed keeping in mind bottle holding comfort, safe feeding and beautiful look.', 249, 229, 'INR', 'https://m.media-amazon.com/images/I/711uwXTijFL._SL1500_.jpg', 122, true, true, now());
 insert into product_details (category_id, name, description, mrp, actual_price, currency_code, image_url, available_stock, in_stock, active, created_date) values (2, 'MOMISY Baby Wash Cloth Face Towel Handkerchief for Baby New Born/Infants/Toddlers (Pack of 5) -Assorted Colours', 'Multipack: 5 The baby wash cloth is made of high quality soft eco-friendly Coral Fleece. The breathable soft material does not irritate the baby’s skin. SAFE TO USE: This material is Anti allergic and safe to use every day. Free from harmful toxics which are main cause of skin irritation in kids. MULTIPURPOSE USE: The soft cloth has a multiple usage. It can be used as baby wash cloth, burp cloth, teething cloth, spit up cloth. Can also be used as Handkerchief while on the go. PERFECT FOR ON-THE-GO: This cloth is perfect to use while on travel. The quick dry and liquid absorbency mechanism make the cloth perfect for on the go. PERFECT SIZE: These muslin baby washcloths are just right to fit into the parent’s hand. They are not too big or not too small. It can be used on both sides. Size: 30 * 30 cm. Package contains: 5 pieces Colour: Assorted', 899, 339, 'INR', 'https://m.media-amazon.com/images/I/518n+wOZ5iL.jpg', 20, true, true, now());
 insert into product_details (category_id, name, description, mrp, actual_price, currency_code, image_url, available_stock, in_stock, active, created_date) values (1, 'Maybelline New York The Blushed Nudes Palette Eyeshadow, 9g', 'Maybelline introduces The Blushed Nudes eyeshadow palette. With 12 shades, you can use the rose -gold infused nude eye shadow palette to create endless, naturalm and barely-there eye makeup looks.', 905, 631, 'INR', 'https://m.media-amazon.com/images/I/71bX9J1gW9L._SL1001_.jpg', 12, true, true, now());
 insert into product_details (category_id, name, description, mrp, actual_price, currency_code, image_url, available_stock, in_stock, active, created_date) values (6, 'Sukkhi Glamorous LCT Gold Plated Wedding Jewellery Pearl Choker Necklace Set Combo For Women (CB73381)', 'This Sukkhi Glamorous Gold Plated Choker Necklace Set Combo For Women is Made Of Alloy. Women Love Jewellery; Specially Traditional Jewellery Adore A Women. They Wear It On Different Occasion. They Have Special Importance On Ring Ceremony, Wedding And Festive Time. They Can Also Wear It On Regular Basics. Make Your Moment Memorable With This Range. This Jewel Set Features A Unique One Of A Kind Traditional Embellish With Antic Finish.', 5645, 284, 'INR', 'https://m.media-amazon.com/images/I/912iX-Sve0L._UL1500_.jpg', 0, false, true, now());
 insert into product_details (category_id, name, description, mrp, actual_price, currency_code, image_url, available_stock, in_stock, active, created_date) values (4, 'LEOTUDE Regular Fit Mens Hoodie Sweatshirt', '', 569, 569, 'INR', 'https://m.media-amazon.com/images/I/716nmUNDRoL._UL1500_.jpg', 68, true, true, now());
 insert into product_details (category_id, name, description, mrp, actual_price, currency_code, image_url, available_stock, in_stock, active, created_date) values (7, 'Mi Smart Band 5 – India’s No. 1 Fitness Band, 1.1 inch (2.8 cm) AMOLED Color Display, Magnetic Charging, 2 Weeks Battery Life, Personal Activity Intelligence (PAI), Women’s Health Tracking', '1.1” Full touch AMOLED color display Battery runs up to 14 days on a single charge. Battery capacity : 125 mAh', 2999, 2499, 'INR', 'https://m.media-amazon.com/images/I/71X8NdnCsvL._SL1500_.jpg', 128, true, true, now());
 insert into product_details (category_id, name, description, mrp, actual_price, currency_code, image_url, available_stock, in_stock, active, created_date) values (6, 'C&G INDIA Balika Vadhu Jewellery Designer Yellow Pink Jwellery Set for Women & Girls (Mehandi/Haldi /Bridal/Baby Shower/Marriage)', 'C&G INDIA Flower jewellery set -Vibrant Colour, Weightless, Soft and Easy to handle -Wearable in Wedding / Party / Baby Shower/ Bridal / Haldi / Mehndi /Baby shower Festive Season. Great surprise for weddings. The flower jewellery is an elegant representation of a timeless bond of love and affection that connects two people. Elegant and classy, this our hand made jewellery makes a beautiful gift option that is sure to show how much you care.', 599, 349, 'INR', 'https://m.media-amazon.com/images/I/81sseeRgRkL._UL1500_.jpg', 2, true, true, now());
 insert into product_details (category_id, name, description, mrp, actual_price, currency_code, image_url, available_stock, in_stock, active, created_date) values (7, 'HP All-in-One 24-df0215in 60.45 cm (23.8-Inch) FHD with Alexa Built-in (AMD Ryzen 3-3250U/8GB/256GB SSD + 1TB HDD/Win 10/MS Office 2019/Jet Black)', 'The HP All-in-One PC blends the power of a desktop with the beauty of a slim, three-sided borderless display for one dependable device designed to grow with you. With easy upgrades[1] in three simple steps, you can feel confident your tech will stay up-to-date.', 51266, 45990, 'INR', 'https://m.media-amazon.com/images/I/71MW1E0je-L._SL1200_.jpg', 10, true, true, now());
 insert into product_details (category_id, name, description, mrp, actual_price, currency_code, image_url, available_stock, in_stock, active, created_date) values (8, 'Giftplease Customized Photo and song Spotify Plaque With Steel Removable Stand | Personalized Printed Frame with scannable code | Gift | Birthday | Anniversary (Black, Acrylic, 6 * 9 Inches)', 'A perfect design acrylic glass customized frame with Steel stand.You can choose your favorite, meaningful or memorable song to tell your feelings to your loved ones.', 1199, 299, 'INR', 'https://m.media-amazon.com/images/I/81lurIgtpUL._SL1500_.jpg', 1, true, true, now());
 insert into product_details (category_id, name, description, mrp, actual_price, currency_code, image_url, available_stock, in_stock, active, created_date) values (5, 'Mamta Decoration Sheesham Wood 4 Seater Dining Table with 3 Chairs and 1 Bench for Living Room', 'The product requires basic self assembly at customers end and comes with self assembly instructions along with necessary accessories. DIY Assembly required the provides assembly at extra cost if service is available at customers city. This splendid style of wooden dining table set create a beautiful impression with perception of modernization.', 20999, 17999, 'INR', 'https://m.media-amazon.com/images/I/61VoVk8ystL._SL1000_.jpg', 10, true, true, now());
 insert into product_details (category_id, name, description, mrp, actual_price, currency_code, image_url, available_stock, in_stock, active, created_date) values (9, 'Samsung 415L 3 Star Inverter Frost Free Double Door Refrigerator (RT42M553ES8/TL, Elegant Inox, Convertible)', '', 62000, 45490, 'INR', 'https://m.media-amazon.com/images/I/71ET8DGKz2L._SL1500_.jpg', 0, false, true, now());
 insert into product_details (category_id, name, description, mrp, actual_price, currency_code, image_url, available_stock, in_stock, active, created_date) values (4, 'KIPEK Womens Cotton Floral Print Regular Wear Top (Black)', 'Our floral print top is perfect for you to dress up and flaunt. The mandarin collar enhances the overall look of this piece. Be it a family function, housewarming, or any festive event you’re definitely gonna slay with this eye-catchy outfit.', 899, 489.02, 'INR', 'https://m.media-amazon.com/images/I/71Ad1HH4pDL._UL1440_.jpg', 26, true, true, now());
 insert into product_details (category_id, name, description, mrp, actual_price, currency_code, image_url, available_stock, in_stock, active, created_date) values (8, 'Woodz Floral Ceramic Plates with Stand, Decorative Wall Plates for Home & Office (Multicolor, Set of 2, Diameter 8 & 10 Inches, woodz_NEW_plt-P02-002)', 'Combo Pack brings to you some elegant Madhubani designer 3D ceramic 10 inch to & Inch plate with vibrant images for a special keepsake gift! Featuring a subtle contour and smooth edge, this plate looks beautiful on a wall or table top. These | Decorative Plates for Home & Office are highly suitable for Home Decor or as a gift for your loved ones. Ergonomically Designed Ceramics Serving To Adorn Your Cuisine Or Kitchen and Guests Table With Style. Durable And handy, It Will Be A Marvelous Addition To Your Culinary Collection. Product Usage: It is an exclusive showpiece for your home, sure to be admired by your family & friends. Comes with a Hook on the back of plate for easy wall hanging. Comes with a Standfor easy display on table.(black/transparent Standas per availibilty) Made in India product!', 2999, 1475, 'INR', 'https://m.media-amazon.com/images/I/81W7WbPqwuL._SL1500_.jpg', 1234, true, true, now());
 insert into product_details (category_id, name, description, mrp, actual_price, currency_code, image_url, available_stock, in_stock, active, created_date) values (9, 'Havells Freddo I Desert Air Cooler', 'Full functional remote : Remote function facility provides user effortless operation of air cooler', 22210, 16999, 'INR', 'https://m.media-amazon.com/images/I/81lFzbC1xOL._SL1500_.jpg', 0, false, true, now());
  